name: Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Get Release Description from config.toml
        uses: SebRollen/toml-action@v1.0.0
        id: release_description
        with: 
          file: 'config.toml'
          field: 'release.name'

      - name: Get Release Version from config.toml
        uses: SebRollen/toml-action@v1.0.0
        id: release_version
        with: 
          file: 'config.toml'
          field: 'release.version'

      - name: Upload as build artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Syncer
          path: src

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with: 
          body: ${{ steps.release_description.outputs.value }}
          tag_name: ${{ steps.release_version.outputs.value }}
          files: Syncer
          draft: true