name: Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        
      - name: Get Release Name from config.toml
        uses: SebRollen/toml-action@v1.0.0
        id: release_name
        with: 
          file: 'config.toml'
          field: 'release.name'

      - name: Get Release Description from config.toml
        uses: SebRollen/toml-action@v1.0.0
        id: release_description
        with: 
          file: 'config.toml'
          field: 'release.name'

      - name: Get Release Tag from config.toml
        uses: SebRollen/toml-action@v1.0.0
        id: release_tag
        with: 
          file: 'config.toml'
          field: 'release.tag'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.release_name.outputs.value }}
          body: ${{ steps.release_description.outputs.value }}
          draft: true
          prerelease: false

      - name: Upload to Github Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "/"
          tag_name: ${{ steps.release_tag.outputs.value }}
          overwrite: true

          tags: true
          draft: true